In [1]:
#  # Import packages

# %matplotlib inline
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import matplotlib as mpl
# from matplotlib import ticker
# from matplotlib import rc
# import seaborn as sns

# # Set the global font to be Arial, size 10
# rc('font',**{'family':'sans-serif','sans-serif':['Arial'],'size':10})

# # Package to read xml files
# from xml.etree import cElementTree as ET

In [2]:
# # This function was adopted from Paulo Caldas, please see: 
# # https://github.com/paulocaldas/How-to-Python/blob/master/Read%20XML%20files%20and%20Plot%20Trajectories%20from%20TrackMate.ipynb


# def read_trackmate_xml_tracks(xml_file):
#     """Reads tracks from trackmate xml track file and returns a DataFrame 
#     in similar format as the trackmate csv, plus the frame interval is returned"""
    
#     tracks = ET.parse(xml_file)
#     frame_interval = float(tracks.getroot().attrib["frameInterval"])
    
#     attributes = []
#     for ti, track in enumerate(tracks.iterfind('particle')):
#         for spots in track.iterfind('detection'):
#             attributes.append([ti, int(spots.attrib.get('t')),
#                                    float(spots.attrib.get('x')),
#                                    float(spots.attrib.get('y'))])
# #         attributes[ti].append(int(track.attrib.get('nSpots')))
        

#     track_table = pd.DataFrame(attributes, columns=['TRACK_ID','FRAME','POSITION_X','POSITION_Y'])
    
#     return track_table, frame_interval, attributes
#     print(attributes)

In [3]:
# data = "D:/190528_particles_gmppnp_100ms_2_1_Tirf640-cam1_Tracks.xml"

# table_particles, frame_interval, attributes = read_trackmate_xml_tracks(data)
# print(table_particles.head(3), '\n...') # Take a look at the table format
# print("Number of tracks:", table_particles['TRACK_ID'].values[-1]+1)

   TRACK_ID  FRAME  POSITION_X  POSITION_Y
0         0      0   19.892656    0.547626
1         0      1   19.887376    0.523813
2         0      2   19.482000    0.000000
...
Number of tracks: 790

In [4]:
# vector_x_list = []
# vector_y_list = []
# for groups, columns in table_particles.groupby('TRACK_ID', sort = False):
#     vector_x = columns['POSITION_X'].diff()
#     vector_x_list.append(vector_x)
#     vector_y = columns['POSITION_Y'].diff()
#     vector_y_list.append(vector_y)

# vector_x_list=[item for sublist in vector_x_list for item in sublist]
# table_particles['VECTOR_X']=vector_x_list
# vector_y_list=[item for sublist in vector_y_list for item in sublist]
# table_particles['VECTOR_Y']=vector_y_list

In [53]:
# theta_list=[]

# for groups, columns in table_particles.groupby('TRACK_ID', sort = False):
#     for i in range(1,columns.shape[0]):
#         vector1 = [table_particles.loc[i-1,'VECTOR_X'],table_particles.loc[i-1,'VECTOR_Y']]
#         vector2 = [table_particles.loc[i,'VECTOR_X'],table_particles.loc[i,'VECTOR_Y']]
# #         print(vector1, vector2)
#         cos_theta = np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2))
#         theta = np.arccos(cos_theta)
# #         print('theta: ', theta)
#         theta_list.append(theta)
#     theta_list.append(np.nan)


# table_particles['THETA'] = theta_list

C:\Users\Urban\anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars

In [54]:
# table_particles

       TRACK_ID  FRAME  POSITION_X  POSITION_Y  VECTOR_X  VECTOR_Y     THETA
0             0      0   19.892656    0.547626       NaN       NaN       NaN
1             0      1   19.887376    0.523813 -0.005280 -0.023813  0.440434
2             0      2   19.482000    0.000000 -0.405376 -0.523813  0.912177
3             0      4   18.564000    0.000000 -0.918000  0.000000  3.141593
4             0      5   18.870000    0.000000  0.306000  0.000000  3.141593
...         ...    ...         ...         ...       ...       ...       ...
34620       788    499    0.700888   38.131459 -0.067997 -0.435091       NaN
34621       789    493   40.408756   18.152142       NaN       NaN       NaN
34622       789    494   40.446127   18.174862  0.037370  0.022720  0.440434
34623       789    495   40.479343   18.181512  0.033216  0.006650  0.912177
34624       789    496   40.461551   18.172677 -0.017792 -0.008835       NaN

[34625 rows x 7 columns]

In [7]:
######################################################################

# An all-in-one script

# Packages

%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import ticker
from matplotlib import rc
import seaborn as sns
# Set the global font to be Arial, size 10
rc('font',**{'family':'sans-serif','sans-serif':['Arial'],'size':10})
# Package to read xml files
from xml.etree import cElementTree as ET
import tkinter as tk
from tkinter import filedialog

######################################################################

# Select a trackmate .xml file

root= tk.Tk()

canvas1 = tk.Canvas(root, width = 320, height = 200, bg = 'lightsteelblue2', relief = 'raised')
canvas1.pack()

# This function was adopted from Paulo Caldas, please see: 
# https://github.com/paulocaldas/How-to-Python/blob/master/Read%20XML%20files%20and%20Plot%20Trajectories%20from%20TrackMate.ipynb


def read_trackmate_xml_tracks(xml_file):
    """Reads tracks from trackmate xml track file and returns a DataFrame 
    in similar format as the trackmate csv, plus the frame interval is returned"""
    
    tracks = ET.parse(xml_file)
    frame_interval = float(tracks.getroot().attrib["frameInterval"])
    
    attributes = []
    for ti, track in enumerate(tracks.iterfind('particle')):
        for spots in track.iterfind('detection'):
            attributes.append([ti, int(spots.attrib.get('t')),
                                   float(spots.attrib.get('x')),
                                   float(spots.attrib.get('y'))])
#         attributes[ti].append(int(track.attrib.get('nSpots')))
        

    track_table = pd.DataFrame(attributes, columns=['TRACK_ID','FRAME','POSITION_X','POSITION_Y'])
    
    return track_table, frame_interval, attributes
    print(attributes)

def getXML_data ():
    global table_particles, frame_interval, attributes
    
    import_file_path = filedialog.askopenfilename()
    table_particles, frame_interval, attributes = read_trackmate_xml_tracks(import_file_path)
#     print(table_particles.head(3), '\n...') # Take a look at the table format
    print("Number of tracks:", table_particles['TRACK_ID'].values[-1]+1)
    
browseButton_CSV = tk.Button(text="      Import particle .xml file     ", command=getXML_data, bg='green', fg='white', font=('arial', 12, 'bold'))
canvas1.create_window(160, 100, window=browseButton_CSV)

root.mainloop()

######################################################################

# Get particle vectors

vector_x_list = []
vector_y_list = []
for groups, columns in table_particles.groupby('TRACK_ID', sort = False):
    vector_x = columns['POSITION_X'].diff()
    vector_x_list.append(vector_x)
    vector_y = columns['POSITION_Y'].diff()
    vector_y_list.append(vector_y)

vector_x_list=[item for sublist in vector_x_list for item in sublist]
table_particles['VECTOR_X']=vector_x_list
vector_y_list=[item for sublist in vector_y_list for item in sublist]
table_particles['VECTOR_Y']=vector_y_list

######################################################################

# Calculate theta angle

theta_list=[]

for groups, columns in table_particles.groupby('TRACK_ID', sort = False):
    for i in range(1,columns.shape[0]):
        vector1 = [table_particles.loc[i-1,'VECTOR_X'],table_particles.loc[i-1,'VECTOR_Y']]
        vector2 = [table_particles.loc[i,'VECTOR_X'],table_particles.loc[i,'VECTOR_Y']]
#         print(vector1, vector2)
        cos_theta = np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2))
        theta = np.arccos(cos_theta)
#         print('theta: ', theta)
        theta_list.append(theta)
    theta_list.append(np.nan)

table_particles['THETA_rad'] = theta_list
table_particles['THETA_deg'] = table_particles['THETA_rad']*180/np.pi

######################################################################

display(table_particles)

######################################################################

#table_particles.to_csv(particle_angles_outputfile.csv)

Number of tracks: 790

C:\Users\Urban\anaconda3\lib\site-packages\ipykernel_launcher.py:96: RuntimeWarning: invalid value encountered in double_scalars

,TRACK_ID,FRAME,POSITION_X,POSITION_Y,VECTOR_X,VECTOR_Y,THETA_rad,THETA_deg
0,0,0,19.892656,0.547626,NaN,NaN,NaN,NaN
1,0,1,19.887376,0.523813,-0.005280,-0.023813,0.440434,25.235016
2,0,2,19.482000,0.000000,-0.405376,-0.523813,0.912177,52.263886
3,0,4,18.564000,0.000000,-0.918000,0.000000,3.141593,180.000000
4,0,5,18.870000,0.000000,0.306000,0.000000,3.141593,180.000000
...,...,...,...,...,...,...,...,...
34620,788,499,0.700888,38.131459,-0.067997,-0.435091,NaN,NaN
34621,789,493,40.408756,18.152142,NaN,NaN,NaN,NaN
34622,789,494,40.446127,18.174862,0.037370,0.022720,0.440434,25.235016
34623,789,495,40.479343,18.181512,0.033216,0.006650,0.912177,52.263886
34624,789,496,40.461551,18.172677,-0.017792,-0.008835,NaN,NaN